# Generated by Django 3.1.5 on 2021-01-06 18:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnas', '0002_dna_mutations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dna', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('mutations', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='DNA',
        ),
    ]
